# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
annotations:
  category: "Security"
  licenses: "AGPL-3.0-only"
apiVersion: "v2"
dependencies:
  - name: "nubus-common"
    version: "0.28.0"
    repository: "oci://artifacts.software-univention.de/nubus-dev/charts"
  - name: "nats"
    version: "0.6.0"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
    condition: "nats.bundled"
description: "A Helm Chart that deploys the provisioning services"
keywords:
  - "provisioning"
name: "provisioning"
sources:
  - "https://git.knut.univention.de/univention/customers/dataport/upx/provisioning/-/tree/main/helm/provisioning?ref_type=heads"
type: "application"
version: "0.45.0"
...
