# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
global:
  configMapUcr: "dummy-ucr-configmap-name"
  systemExtensions:
    - name: "portal"
      image:
        repository: "nubus/images/portal-extension"
        tag: "0.44.3@sha256:734efc0adda680526dde09387db964612f9e0ab020382580984488cc993c68f0"


resources:
  dispatcher:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  prefill:
    config:
      UDM_HOST: "udm-host"
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  api:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  udmTransformer:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"

api:
  nats:
    auth:
      password: "linter-api-nats-password"

dispatcher:
  nats:
    auth:
      password: "linter-dispatcher-nats-password"

udmTransformer:
  nats:
    auth:
      password: "linter-udm-transformer-nats-password"
  ldap:
    connection:
      host: "ldap-host"
      port: "1234"
    baseDn: "ldap-base-dn"
    auth:
      password: "linter-udm-transformer-ldap-password"

prefill:
  config:
    UDM_HOST: "udm-host"
  nats:
    auth:
      password: "linter-prefill-nats-password"
  udm:
    auth:
      password: "linter-prefill-udm-password"

registerConsumers:
  provisioningApiBaseUrl: "provisioning-base-url"
  createUsers:
    portal-consumer:
      existingSecret:
        name: "linter-portal-consumer-provisioning-api"
        keyMapping:
          registration: null
  udm:
    auth:
      password: "linter-register-consumers-udm-password"

nats:
  bundled: false
  connection:
    host: "linter-nats-host"
    port: "linter-nats-port"
  extraEnvVars:
    - name: NATS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "dummy-nats-admin-secret-name"
          key: "dummy-nats-admin-secret-key"
    - name: NATS_PROVISIONING_API_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "dummy-nats-provisioning-api-secret-name"
          key: "dummy-nats-provisioning-api-secret-key"
    - name: NATS_DISPATCHER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "dummy-nats-dispatcher-secret-name"
          key: "dummy-nats-dispatcher-secret-key"
    - name: NATS_UDM_TRANSFORMER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "dummy-nats-udm-transformer-secret-name"
          key: "dummy-nats-udm-transformer-secret-key"
    - name: NATS_PREFILL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "dummy-nats-prefill-secret-name"
          key: "dummy-nats-prefill-secret-key"
...
