# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---
global:
  secrets:
    masterPassword: "nubus"
  configMapUcr: "dummy-ucr-configmap-name"
  systemExtensions:
    - name: "portal"
      image:
        repository: "nubus/images/portal-extension"
        tag: "0.44.3@sha256:734efc0adda680526dde09387db964612f9e0ab020382580984488cc993c68f0"


resources:
  dispatcher:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  prefill:
    config:
      UDM_HOST: "udm-host"
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  api:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"
  udmTransformer:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"

udmTransformer:
  ldap:
    connection:
      host: "ldap-host"
      port: "1234"
    auth:
      password: "linter-udm-transformer-ldap-password"
  nats:
    auth:
      password: "stub-value"

prefill:
  config:
    UDM_HOST: "udm-host"
  udm:
    auth:
      password: "linter-prefill-udm-password"
  nats:
    auth:
      password: "stub-value"

dispatcher:
  nats:
    auth:
      password: "stub-value"

api:
  nats:
    auth:
      password: "stub-value"

registerConsumers:
  provisioningApiBaseUrl: "provisioning-base-url"
  createUsers:
    portal-consumer:
      existingSecret:
        name: "linter-portal-consumer-provisioning-api"
        keyMapping:
          registration: null
  udm:
    auth:
      password: "linter-register-consumers-udm-password"

# Required when nats.bundled: false is set
nats:
  connection:
    host: "linter-nats-host"
    port: "linter-nats-port"
...
