workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "webide"
    - if: $CI_COMMIT_TAG

include:
  - project: univention/dev/ucs
    file: .gitlab-ci/base.yml
  - project: univention/infrastructure/docker-services
    file: kaniko.yml
  - project: univention/infrastructure/docker-services
    file: pre-commit.yml
  - local: fragments/misc.yaml

stages:
  - build
  - release
  - cleanup

run_pre_commit:
  stage: build
  needs: []
  extends: .pre-commit

lint_commit_messages:
  stage: build
  needs: []
  extends: .lint_commit_messages

build_ec2_tools:
  stage: build
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "images/ec2-tools.Containerfile"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/ec2-tools"
    DOCKERFILE_PATH: "images/ec2-tools.Containerfile"

build_pre_commit:
  stage: build
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "images/pre-commit.Containerfile"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/pre-commit"
    DOCKERFILE_PATH: "images/pre-commit.Containerfile"

build_prek:
  stage: build
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "images/prek.Containerfile"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/prek"
    DOCKERFILE_PATH: "images/prek.Containerfile"


build_univention_appcenter_control:
  stage: build
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "images/univention-appcenter-control.Containerfile"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/univention-appcenter-control"
    DOCKERFILE_PATH: "images/univention-appcenter-control.Containerfile"

build_python:
  stage: build
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "images/python/**/*"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/python"
    DOCKERFILE_PATH: "images/python/python.Containerfile"
    KANIKO_BUILD_CONTEXT: "images/python"

build_uv:
  stage: build
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "images/uv/**/*"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/uv"
    DOCKERFILE_PATH: "images/uv/uv.Containerfile"
    KANIKO_BUILD_CONTEXT: "images/uv"

build_allure:
  stage: build
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "images/allure/**/*"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/allure"
    DOCKERFILE_PATH: "images/allure/allure.Containerfile"
    KANIKO_BUILD_CONTEXT: "images/allure"

build_app_release:
  stage: build
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "images/app-release/**/*"
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/app-release"
    DOCKERFILE_PATH: "images/app-release/app-release.Containerfile"
    KANIKO_BUILD_CONTEXT: "images/app-release"

.build_deb_builder:
  stage: build
  extends: .kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "images/deb-builder/**/*"
  variables:
    DOCKERFILE_PATH: "images/deb-builder/deb-builder.Containerfile"
    KANIKO_BUILD_CONTEXT: "images/deb-builder"

build_deb_builder52:
  extends: .build_deb_builder
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/deb-builder-5.2"
    KANIKO_ARGS: "--build-arg UCSVERSION=$ucs"

build_deb_builder50:
  extends: .build_deb_builder
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/deb-builder-5.0"
    KANIKO_ARGS: "--build-arg UCSVERSION=5010"

release_cicd_components:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/'
  script:
    - echo "Releasing for $CI_COMMIT_TAG."
  release:
    tag_name: $CI_COMMIT_TAG
    name: "CI/CD Components: $CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG_MESSAGE"
