# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

services:
  provisioning-api:
    image: gitregistry.knut.univention.de/univention/dev/projects/provisioning/provisioning-events-and-consumer-api-test:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/events-and-consumer-api/Dockerfile
      target: test
      # args:
      #   - UCS_BASE_IMAGE_TAG=latest
    container_name: "provisioning-api"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats2"
      NATS_PORT: "4222"
      NATS_USER: "api"
      NATS_PASSWORD: "apipass"
      NATS_MAX_RECONNECT_ATTEMPTS: 2
      ADMIN_NATS_USER: "admin"
      ADMIN_NATS_PASSWORD: "univention"
      UDM_HOST: "udm-rest-api"
      UDM_PORT: 9979
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "provisioning"
      PREFILL_USERNAME: "prefill"
      PREFILL_PASSWORD: "prefillpass"
      MAX_PREFILL_ATTEMPTS: 5
      EVENTS_USERNAME_UDM: "udm"
      EVENTS_PASSWORD_UDM: "udmpass"
      DEBUG: "false"
      ROOT_PATH: "/"
      CORS_ALL: "false"
    depends_on:
      - "nats2"
    ports:
      - "7777:7777"
    volumes:
      - coverage-data:/coverage:rw

  nats1:
    image: "nats:latest"
    container_name: nats1
    environment:
      jetstream: "enabled"
    ports:
      - "4222:4222"
      - "8222:8222" # HTTP monitoring port
    volumes:
      - ./nats.dev.conf:/etc/nats-config/nats.conf
      - type: tmpfs
        target: /var/run
    command: --name nats1 --cluster_name JetStreamCluster --jetstream -m 8222 -p 4222 -config /etc/nats-config/nats.conf --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245,nats://nats3:4245
  nats2:
    image: nats:latest
    container_name: nats2
    command: --name nats2 --cluster_name JetStreamCluster --jetstream -m 8222 -p 4222 -config /etc/nats-config/nats.conf --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245,nats://nats3:4245
    volumes:
      - ./nats.dev.conf:/etc/nats-config/nats.conf
      - type: tmpfs
        target: /var/run
  nats3:
    image: nats:latest
    container_name: nats3
    command: --name nats3 --cluster_name JetStreamCluster --jetstream -m 8222 -p 4222 -config /etc/nats-config/nats.conf --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245,nats://nats3:4245
    volumes:
      - ./nats.dev.conf:/etc/nats-config/nats.conf
      - type: tmpfs
        target: /var/run


  dispatcher:
    image: gitregistry.knut.univention.de/univention/dev/projects/provisioning/provisioning-dispatcher-test:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/dispatcher/Dockerfile
      # args:
      #   - UCS_BASE_IMAGE_TAG=latest
      target: test
    container_name: "provisioning-dispatcher"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats3"
      NATS_PORT: "4222"
      NATS_USER: "dispatcher"
      NATS_PASSWORD: "dispatcherpass"
      NATS_MAX_RECONNECT_ATTEMPTS: 2
      PROVISIONING_API_HOST: "provisioning-api"
      PROVISIONING_API_PORT: 7777
    depends_on:
      - "nats3"
      - "provisioning-api"
    volumes:
      - coverage-data:/coverage:rw

  udm-transformer:
    image: "gitregistry.knut.univention.de/univention/dev/projects/provisioning/provisioning-udm-transformer-test:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/udm-transformer/Dockerfile
      # args:
      #   - UCS_BASE_IMAGE_TAG=latest
      target: test
    container_name: "provisioning-udm-transformer"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats1"
      NATS_PORT: "4222"
      NATS_USER: "udm-transformer"
      NATS_PASSWORD: "udm-transformerpass"
      # LDAP_PUBLISHER_NAME: "ldif-producer"
      LDAP_PUBLISHER_NAME: "udm-listener"

      PROVISIONING_API_HOST: "provisioning-api"
      PROVISIONING_API_PORT: 7777
      EVENTS_USERNAME_UDM: "udm"
      EVENTS_PASSWORD_UDM: "udmpass"

      LDAP_HOST: "ldap-server"
      LDAP_PORT: 389
      LDAP_TLS_MODE: "off"
      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
      LDAP_BIND_DN: "cn=admin,dc=univention-organization,dc=intranet"
      LDAP_BIND_PW: "univention"
    depends_on:
      - "nats1"
      - "provisioning-api"
    volumes:
      - coverage-data:/coverage:rw

  prefill:
    image: "gitregistry.knut.univention.de/univention/dev/projects/provisioning/provisioning-prefill-test:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/prefill/Dockerfile
      # args:
      #   - UCS_BASE_IMAGE_TAG=latest
      target: test
    container_name: "provisioning-prefill"
    restart: "on-failure"
    environment:
      LOG_LEVEL: "DEBUG"
      NATS_HOST: "nats2"
      NATS_PORT: "4222"
      PROVISIONING_API_HOST: "provisioning-api"
      PROVISIONING_API_PORT: 7777
      NATS_USER: "prefill"
      NATS_PASSWORD: "prefillpass"
      NATS_MAX_RECONNECT_ATTEMPTS: 2
      UDM_HOST: "udm-rest-api"
      UDM_PORT: 9979
      UDM_USERNAME: "cn=admin"
      UDM_PASSWORD: "univention"
      PREFILL_USERNAME: "prefill"
      PREFILL_PASSWORD: "prefillpass"
      MAX_PREFILL_ATTEMPTS: 5
    depends_on:
      - "nats2"
      - "provisioning-api"
    volumes:
      - coverage-data:/coverage:rw

  ldif-producer:
    platform: linux/amd64
    container_name: "ldif-producer"
    image: "gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/ldap/ldif-producer:latest"
    # Can be uncommented to simplify local development.
    # build:
    #   dockerfile: ../container-ldap/docker/ldif-producer/Dockerfile
    #   context: ../container-ldap/
    environment:
      SOCKET_FILE_LOCATION: "/var/lib/univention-ldap/slapd-sock/sock"
      NATS_USER: ldif-producer
      NATS_PASSWORD: ldifpass
      NATS_HOST: "nats3"
      NATS_PORT: "4222"
      NATS_MAX_RECONNECT_ATTEMPTS: 2
      MAX_IN_FLIGHT_LDAP_MESSAGES: 10
      BACKPRESSURE_WAIT_TIMEOUT: 10
      LDAP_THREADS: 5
      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
      IGNORE_TEMPORARY_OBJECTS: "true"
    volumes:
      - ./tests/base-defaults.conf:/etc/univention/base-defaults.conf:ro
      - ldap-socket:/var/lib/univention-ldap/slapd-sock/:rw

  udm-listener:
    image: "gitregistry.knut.univention.de/univention/dev/projects/provisioning/provisioning-udm-listener-test:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/udm-listener/Dockerfile
      # args:
      #   - LISTENER_BASE_IMAGE_TAG=latest
      #   - UCS_BASE_IMAGE_TAG=latest
      target: test
    container_name: "udm-listener"
    volumes:
      - coverage-data:/coverage:rw
      - /etc/ldap/
    environment:
      NATS_HOST: "nats1"
      NATS_PORT: "4222"
      NATS_USER: ldif-producer
      NATS_PASSWORD: ldifpass
      NATS_MAX_RECONNECT_ATTEMPTS: 2
      LDAP_HOST: "ldap-server"
      LDAP_BASE_DN: "dc=univention-organization,dc=intranet"
      LDAP_HOST_DN: "cn=admin,dc=univention-organization,dc=intranet"
      NOTIFIER_SERVER: "ldap-notifier"
      DEBUG_LEVEL: "3"
      TLS_MODE: "off"
      LDAP_PASSWORD_FILE: "/var/secrets/ldap_password"
      LDAP_PORT: 389
    depends_on:
      - "nats1"
      - "ldap-server"
      - "ldap-notifier"

  ldap-notifier:
    platform: linux/amd64
    image: artifacts.software-univention.de/nubus-dev/images/ldap-notifier:0.16.1-pre-jlohmer-bump-to-508
    container_name: "ldap-notifier"
    depends_on:
      ldap-server:
        condition: service_started
    ports:
      - 6669:6669
    volumes:
      - ldap-shared-data:/var/lib/univention-ldap/:rw
      - ldap-shared-run:/var/run/slapd/:ro

  ldap-server:
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/ldap/ldap-server:latest
    container_name: "ldap-server"
    environment:
      LDAP_CN_ADMIN_PW: univention
      LDAP_BASEDN: "dc=univention-organization,dc=intranet"
      PYTHON_LOG_LEVEL: "DEBUG"
      UPDATE_INDEX_ON_STARTUP: "true"
    ports:
      - 389:389
      - 636:636
    volumes:
      - ldap-shared-data:/var/lib/univention-ldap/:rw
      - ldap-shared-run:/var/run/slapd/:rw
      - ${LDAP_SOCKET_LOCATION:-ldap-socket}:/var/lib/univention-ldap/slapd-sock/:rw
      - ./tests/base-defaults.conf:/etc/univention/base-defaults.conf:ro

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap-server':{'login':{'bind_id':'cn=admin,dc=univention-organization,dc=intranet'}}}]"
      PHPLDAPADMIN_HTTPS: "false"
    links:
      - ldap-server
    ports:
      - 8001:80

  udm-rest-api:
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/udm-rest-api/udm-rest-api:latest
    container_name: "udm-rest-api"
    platform: "linux/amd64"
    ports:
      - 9979:9979
    volumes:
      - ./tests/base.conf:/etc/univention/base.conf:ro
    environment:
      DOMAINNAME: univention-organization.intranet
      HOSTNAME: localhost:9979
      LDAP_HOST: ldap-server
      LDAP_PORT: 389
      LDAP_BASE_DN: dc=univention-organization,dc=intranet
      LDAP_HOST_DN: cn=admin,dc=univention-organization,dc=intranet
      TLS_MODE: "off"
      MACHINE_SECRET: univention
      LDAP_CN_ADMIN_PW: univention

  example-client:
    image: "gitregistry.knut.univention.de/univention/dev/projects/provisioning/provisioning-example-client:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/example-client/Dockerfile
      # args:
      #   - UCS_BASE_IMAGE_TAG=latest
    container_name: example-client
    environment:
      PROVISIONING_API_USERNAME: "example-client"
      PROVISIONING_API_PASSWORD: "password"
      PROVISIONING_API_BASE_URL: "http://provisioning-api:7777"
      LOG_LEVEL: "DEBUG"
      MAX_ACKNOWLEDGEMENT_RETRIES: 3
    restart: "on-failure"

  e2e-test:
    image: "gitregistry.knut.univention.de/univention/dev/projects/provisioning/e2e-tests:${IMAGE_TAG:-latest}"
    build:
      context: .
      dockerfile: docker/e2e-test/Dockerfile
    command: ["pytest", "-lvv", "--timeout=300", "--environment", "pipeline"]
    profiles:
      - test
    platform: "linux/amd64"
    volumes:
      - "./e2e_tests/tests:/app/e2e_tests/tests:ro"
      - "./e2e_tests/e2e_settings.json.example:/app/e2e_tests/e2e_settings.json:ro"

  coverage-reporter:
    image: "gitregistry.knut.univention.de/univention/dev/projects/provisioning/testrunner-coverage:${IMAGE_TAG:-latest}"
    container_name: "coverage-reporter"
    build:
      context: .
      dockerfile: docker/test/Dockerfile
      target: coverage
    volumes:
      - coverage-data:/coverage:ro

  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/dev/tooling/pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

  # Environment to build the documentation
  docs:
    image: docker-registry.knut.univention.de/sphinx:latest
    working_dir: /src/docs
    volumes:
      - ".:/src"
    profiles:
      - docs

volumes:
  coverage-data:
  ldap-shared-data:
  ldap-shared-run:
  pre-commit-cache:
  ldap-socket:
