# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: "v2"
type: "application"
name: "example-client"
description: "A Helm chart for the example client of the UDM provisioning API"
home: "https://www.univention.de/"

# Chart version
# Apply Semantic Versioning (https://semver.org/)
version: "0.1.0"

dependencies:
  - name: "nubus-common"
    version: "^0.8.x"
    repository: "oci://artifacts.software-univention.de/nubus/charts"

...
