# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-api" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
      {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
      {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-api" (include "common.names.fullname" .)) }}
      {{- $mergedLabels := merge $uiLabels $commonLabels}}
      {{- toYaml $mergedLabels | nindent 4 }}
    {{- if .Values.api.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.api.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.api.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.api.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      {{- $commonLabels := include "common.labels.matchLabels" . | fromYaml }}
      {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-api" (include "common.names.fullname" .)) }}
      {{- merge $uiLabels $commonLabels | toYaml | nindent 6 }}
  {{- if .Values.updateStrategy.type }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.api.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.api.podAnnotations "context" .) | nindent 8 }}
        {{- end }}
      labels:
        {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
        {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-api" (include "common.names.fullname" .)) }}
        {{- $mergedLabels := merge $uiLabels $commonLabels}}
        {{- toYaml $mergedLabels | nindent 8 }}
    spec:
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets  }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        - name: wait-for-nats
          command: [ "python3", "/scripts/wait-for-nats.py" ]
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          image: "{{ coalesce .Values.api.image.registry .Values.global.imageRegistry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.api.image.pullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-common" (include "common.names.fullname" .) }}
            - configMapRef:
                name: {{ printf "%s-api" (include "common.names.fullname" .) }}
          env:
            - name: NATS_USER
              value: {{ tpl (required "api.nats.auth.username is required" .Values.api.nats.auth.username) . }}
            - name: NATS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.api.nats.auth.existingSecret "defaultNameSuffix" "api-nats" "context" .) }}
                  key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.api.nats.auth.existingSecret "key" "password") }}
          volumeMounts:
            - name: wait-for-nats
              mountPath: /scripts
          {{- if .Values.resources.api }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.resources.api "context" .) | nindent 12 }}
          {{- end }}
      containers:
        - name: "main"
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.api.image.registry .Values.global.imageRegistry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.api.image.pullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-common" (include "common.names.fullname" .) }}
            - configMapRef:
                name: {{ printf "%s-api" (include "common.names.fullname" .) }}
          env:
            - name: ADMIN_USERNAME
              value: "admin"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.api.auth.admin.existingSecret "defaultNameSuffix" "api-admin" "context" .) }}
                  key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.api.auth.admin.existingSecret "key" "password") }}
            - name: EVENTS_USERNAME_UDM
              value: "udm"
            - name: EVENTS_PASSWORD_UDM
              valueFrom:
                secretKeyRef:
                  name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.api.auth.eventsUdm.existingSecret "defaultNameSuffix" "api-events" "context" .) }}
                  key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.api.auth.eventsUdm.existingSecret "key" "password") }}
            - name: PREFILL_USERNAME
              value: "prefill"
            - name: PREFILL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.api.auth.prefill.existingSecret "defaultNameSuffix" "api-prefill" "context" .) }}
                  key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.api.auth.prefill.existingSecret "key" "password") }}
            - name: ADMIN_NATS_USER
              value: "placeholder"
            - name: ADMIN_NATS_PASSWORD
              value: "placeholder"
            - name: NATS_USER
              value: {{ tpl (required "api.nats.auth.username is required" .Values.api.nats.auth.username) . }}
            - name: NATS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.api.nats.auth.existingSecret "defaultNameSuffix" "api-nats" "context" .) }}
                  key: {{ include "nubus-common.secrets.key" (dict "existingSecret" .Values.api.nats.auth.existingSecret "key" "password") }}
          {{- with .Values.extraEnvVars }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.api.enabled }}
          livenessProbe: {{- omit .Values.livenessProbe.api "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.api.enabled }}
          readinessProbe: {{- omit .Values.readinessProbe.api "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.api.enabled }}
          startupProbe: {{- omit .Values.startupProbe.api "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            {{- range $key, $value := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          {{- if .Values.resources.api }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.resources.api "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.lifecycleHooks "context" .) | nindent 12 }}
          {{- end }}
          {{- if or .Values.nats.connection.tls.enabled .Values.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.nats.connection.tls.enabled }}
            - name: certificates-volume
              mountPath: /certificates
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" .) | nindent 12 }}
            {{- end }}
          {{- end }}
      volumes:
        - name: wait-for-nats
          configMap:
            name: {{ printf "%s-api" (include "common.names.fullname" .) }}
        {{- if .Values.nats.connection.tls.enabled }}
        - name: certificates-volume
          secret:
            secretName: {{ .Values.nats.connection.tls.secretName  | default (printf "%s-api-tls" (include "common.names.fullname" .) ) }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes  "context" .) | nindent 8 }}
        {{- end }}
