{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- $secretName := (include "nubus-common.secrets.name" (dict "defaultNameSuffix" "prefill-nats" "context" . )) }}

{{- $gen := printf "nbs_%s" (print (derivePassword 1 "long" .Values.global.secrets.masterPassword "nubus" "provisioning-prefill") | sha1sum) }}
{{- $password := default $gen .Values.prefill.nats.auth.password }}

{{- if not (.Values.prefill.nats.auth.existingSecret).name }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "prefill-nats" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
stringData:
  password: {{ $password | quote }}
{{- end }}
