{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- $_ := required
  "A UDM password has to be supplied, see parameter prefill.udm.auth."
  ( coalesce .Values.prefill.udm.auth.password (.Values.prefill.udm.auth.existingSecret).name )
  }}
{{- if not (.Values.prefill.udm.auth.existingSecret).name }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "prefill-udm" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
stringData:
  password: {{ .Values.prefill.udm.auth.password | quote }}
{{- end }}
