{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- $_ := required "A Nats password is required, see parameter api.nats.auth." (coalesce .Values.api.nats.auth.password .Values.global.secrets.masterPassword (.Values.api.nats.auth.existingSecret).name) }}
{{- if not (.Values.api.nats.auth.existingSecret).name }}
{{- $secretName := (include "nubus-common.secrets.name" (dict "defaultNameSuffix" "nats-api" "context" .)) }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- $extraAnnotations := dict }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list $extraAnnotations .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
stringData:
  password: {{ coalesce
    (.Values.api.nats.auth).password
    (printf "nbs_%s" (print (derivePassword 1 "long" .Values.global.secrets.masterPassword "nubus" "provisioning-api") | sha1sum)
  ) | quote }}
{{- end }}
