#!/bin/bash
#
# App join script
#
# Copyright 2021-2025 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.


## joinscript api: bindpwdfile

VERSION=1
. /usr/share/univention-join/joinscripthelper.lib
. /usr/share/univention-lib/all.sh

joinscript_init

SERVICE="provisioning-service"
ucs_addServiceToLocalhost "$SERVICE" "$@"

wait_for_nats () {
    local i=0
    nats_server="localhost:8222/healthz"
    for ((i=0; i<30; i++)); do
        if curl -sf $nats_server > /dev/null; then
            echo "[wait_for_nats]: NATS at $nats_server is responsive."
            return 0
        fi
        echo "[wait_for_nats]: Waiting for NATS at $nats_server ..."
        sleep 1
    done
    echo "[wait_for_nats]: Timeout after 30s - could not reach $nats_server."
    return 1
}

wait_for_nats || die

systemctl restart univention-directory-listener


joinscript_save_current_version

exit 0
