#! /bin/sh
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

## joinscript api: bindpwdfile

VERSION=1

. /usr/share/univention-join/joinscripthelper.lib
. /usr/share/univention-lib/all.sh

joinscript_init

SERVICE="provisioning-service"


# remove service
ucs_removeServiceFromLocalhost "$SERVICE" "$@"

joinscript_remove_script_from_status_file $SERVICE

exit 0
