# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

import pytest
from univention.testing.helm.auth_flavors.password_usage import AuthPasswordUsageViaEnv
from univention.testing.helm.auth_flavors.secret_generation import AuthSecretGenerationOwner
from univention.testing.helm.auth_flavors.nats import NatsCreateUserMixin


class Config:

    workload_kind = "StatefulSet"
    workload_name = "release-name-nats"
    config_map_name = "release-name-nats-config"
    secret_name = "release-name-nats-admin"

    prefix_mapping = {"config.createUsers.adminUser.auth": "auth"}


class TestAdminPassword(Config, NatsCreateUserMixin, AuthSecretGenerationOwner, AuthPasswordUsageViaEnv):
    derived_password = "nbs_c93dea8739b56990984eacba5058b20adfeeb320"

    env_password = "ADMINUSER"
    sub_path_env_password = "env[?@name=='ADMINUSER']"

    @pytest.mark.skip("Nats passwords are required to start with a letter. Random password generation is not supported.")
    def test_auth_password_has_random_value(self, chart): ...

    @pytest.mark.skip("The Admin password can be generated by the chart.")
    def test_auth_existing_secret_is_required(self, chart): ...


class TestAdminPasswordNatsBox(Config, AuthPasswordUsageViaEnv):

    def adjust_values(self, values: dict):

        values.setdefault("natsBox", {})["enabled"] = True
        values.setdefault("reloader", {})["enabled"] = True

        return values

    path_container = "..spec.template.spec.containers[?@.name=='nats-box']"
    sub_path_env_password = "env[?@name=='NATS_PASSWORD']"
